# Generated by Django 4.0.6 on 2022-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Můj zatraceně skvělý Blog!', max_length=255),
        ),
    ]
